server:
  port: 9400
spring:
  cloud:
    nacos:
      discovery:
        server-addr: vm:8848
  datasource:
    url: jdbc:mysql://vm:3306/hxds?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: vm
      port: 6379