spring:
  profiles:
    active: dev
  application:
    name: hxds-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:/mapper/*.xml