spring:
  profiles:
    active: dev
  application:
    name: hxds-gateway
  cloud:
    gateway:
      routes:
        - id: hxds-bff-driver
          predicates:
            - Path=/driver/**
          uri: lb://hxds-bff-driver
        - id: hxds-bff-customer
          predicates:
            - Path=/customer/**
          uri: lb://hxds-bff-customer
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
